config/routes.rb
Blog::Application.routes.draw do
  get "ajax/edit_post"
  match "edit_post" => "ajax#edit_post", :as => "edit_post"

  get "post/new"
  match "new_post" => "post#new", :as => "new_post"

  get "post/detail"

  get "post/edit"

  get "post/delete"
  match "delete_post/:id" => "post#delete", :as => "delete_post"

  get "user/login"
  match "login" => "user#login", :as => "login"

  get "user/logout"
  match "logout" => "user#logout", :as => "logout"

  get "user/profile"
  match "profile" => "user#profile", :as => "profile"

  get "user/signup"
  match "signup" => "user#signup", :as => "signup"

  get "home/index"

  root :to => "home#index"

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :tmp
	self.primary_key = :user_id
	has_many :post
	has_many :comment
	validates_confirmation_of :password, :message => 'Password doesn\'t match !', :if => :not_update_profile?
	validates_presence_of :password_confirmation, :message => 'Re-password is blank !', :if => :not_update_profile?
	validates_presence_of :username, :message => 'Email is blank !', :on => :create
	validates_presence_of :password, :message => 'Password is blank !', :if => :not_update_profile?
	validates_uniqueness_of :username, :case_sensitive => false, :message => 'Email had exist !', :on => :create
	validates_format_of :username, :with => /^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/, :message => "Email isn't invalid !", :on => :create
	validates_length_of :password, :in => 6..20, :message => 'Password has 6 to 20 characters !', :if => :not_update_profile?
	validates_length_of :username, :maximum => 50, :message => 'Email has 50 characters maximum !', :on => :create
	before_save :md5_password
	private
	def md5_password
		if !@tmp.nil?
			if @tmp[:action] == "update" && self[:password] == ""
				self[:password]= @tmp[:password] 
			else
				self[:password]= Digest::MD5.hexdigest(self[:password])
			end
		else
			self[:password]= Digest::MD5.hexdigest(self[:password])
		end
	end

	def not_update_profile?
		if !@tmp.nil?
			if @tmp[:action] == "update" && self[:password] == ""
				false
			else
				true
			end
		else
			true
		end
	end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :require_login, :only => [:profile,:logout]

  def login
    if !params[:data].nil?
      if !params[:data][:username].empty? && !params[:data][:password].empty?
        @user = User.all(:conditions => ["username = ? AND password = ?", params[:data][:username],Digest::MD5.hexdigest(params[:data][:password])])
        if @user.empty?
          flash[:error] = "Wrong username or password !"
          redirect_to root_path
          return
        else
          session[:login] = params[:data][:username]
        end
      else
        flash[:error] = "Please fill username or password !"
        redirect_to root_path
        return
      end
    end
    redirect_to profile_path
  end

  def logout
    session[:login] = nil;
    redirect_to root_path
  end

  def profile
    @page = "profile"
    @title = "Profile"
    if !params[:user].nil?
      begin
        if params[:user][:avatar].nil?
          params[:user][:avatar] = @user[:avatar]
        else
          File.open("#{RAILS_ROOT}/public/data/#{session[:login]}.png","w+") do |f|
                f.write params[:user][:avatar].read
          end
          params[:user][:avatar] ="/data/#{session[:login]}.png"
        end
        if params[:user][:username].nil?
          @user.tmp = {:action => "update", :password => @user[:password]}
        end
        @user.update_attributes(params[:user])
        if @user.errors.empty?
          flash[:success] = 'Update your profile successful !'
          redirect_to profile_path
        end
      rescue Exception => e
        flash[:warning] = 'Can not update profile now, please try again !'
      end    
    end
  end

  def signup
  	@page = "signup"
  	@title = "Sign Up"

  	if !params[:user].nil?
  		@new_user = User.new(params[:user])
  		@new_user.save
      if @new_user.errors.empty?
        session[:login] = params[:user][:username]
        redirect_to profile_path
      end
  	else 
  		@new_user = User.new
  	end
  end

  private
  def require_login
    if !has_login?
      redirect_to root_path
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
	def signup_error
		if !@new_user.errors.empty? 
			html = '<div class="alert alert-error fade in">'
		    html += '	<button type="button" class="close" data-dismiss="alert">x</button>'
		    html += '	Errors :'
		    html += '	<ul>'
				@new_user.errors.each do |e| 
		    		html += "	<li>#{e[1]}</li> "
		    	end 
		    	html += '</ul>'
		    html += '</div>'
		end
		raw html
	end

	def status_input(current)
		if !@new_user.errors[current].empty?
			raw 'class="control-group error"'
		else
			raw 'class="control-group"'
		end
	end

	def login_error 
		if !flash[:error].nil?
			html = '<div class="alert alert-error fade in">'
		    html += '<button type="button" class="close" data-dismiss="alert">x</button>'
		    html += flash[:error]
		    html += '</div>'
		end
		raw html
	end

	def show_avatar(avatar)
		if avatar.nil?
			"#"
		else
			avatar
		end
	end

	def profile_error
		if !@user.errors.empty? 
			html = '<div class="alert alert-error fade in">'
		    html += '	<button type="button" class="close" data-dismiss="alert">x</button>'
		    html += '	Errors :'
		    html += '	<ul>'
				@user.errors.each do |e| 
		    		html += "	<li>#{e[1]}</li> "
		    	end 
		    	html += '</ul>'
		    html += '</div>'
		elsif !flash[:success].nil?
			html = '<div class="alert alert-success fade in">'
		    html += '	<button type="button" class="close" data-dismiss="alert">x</button>'
		    html += flash[:success]
		    html += '</div>'
		elsif !flash[:warning].nil?
			html = '<div class="alert alert-warning fade in">'
		    html += '	<button type="button" class="close" data-dismiss="alert">x</button>'
		    html += flash[:warning]
		    html += '</div>'
		end
		raw html
	end
end

app/views/user/_info.html.erb
<%= image_tag show_avatar(avatar),:onerror => "this.src='/data/no-image.jpg'", :class => "img-polaroid", :width => "97%" %><br/>
<br/>

<%= form_for @new_post, :url => new_post_path do |f| %>
<%= f.text_area :content, :placeholder => "What's on your mind ?", :rows => "3", :style => "width:95%", :maxlength => "500" %>
<%= hidden_field_tag "current_path", request.fullpath %>
<%= post_error %>
<button class="btn btn-large btn-block btn-primary" type="button" onclick="post_comment()">Post</button>
<% end %>
<script type="text/javascript">
	function post_comment(){
		if($("#post_content").val()!="")
			$("#new_post").submit();
	}
</script>

app/views/user/_login.html.erb
							 <%= form_tag login_path, :method => "post", :class => "form" do %>
							    <div class="control-group">
								    <label class="control-label" for="inputEmail">Email</label>
								    <div class="controls">
								    	<%= text_field_tag "data[username]", nil, :class => "input-xlarge", :placeholder => "Email" %> 
								    </div>
								</div>
								<div class="control-group">
								    <label class="control-label" for="inputPassword">Password</label>
									<div class="controls">
										<%= text_field_tag "data[password]", nil, :class => "input-xlarge", :placeholder => "Password", :type => "password" %> 
									</div>
								</div>
						    	<%= login_error %>
								<div class="control-group">
									<div class="controls">
										<%= submit_tag "Sign In",  :class => "btn", :style => "width:80px;" %>
									</div>
							    </div>
						    <% end %>

app/views/user/logout.html.erb
<h1>User#logout</h1>
<p>Find me in app/views/user/logout.html.erb</p>

app/views/user/profile.html.erb
	<%= render :partial =>"home/breadcrum", :locals => { :current_page => @title} %>
	<h2>Edit Profile</h2>

	<%= profile_error %>

    <%= form_for @user, :url => profile_path, :html => { :class => "form-horizontal" , :multipart => true } do |f| %>
	    <div class="control-group" >
		    <label class="control-label">Password</label>
		    <div class="controls">
		    	<%= text_field_tag "user[password]", "", :placeholder => "Password", :type => "password"  %>
		    </div>
	    </div>
	    <div class="control-group" >
		    <label class="control-label">Re-Password</label>
		    <div class="controls">
		    	<%= f.text_field :password_confirmation, :placeholder => "Re-Password", :type => "password"  %>
		    </div>
	    </div>
	    <div class="control-group" >
		    <label class="control-label">Avatar</label>
		    <div class="controls">
		    	<%= image_tag show_avatar(@user[:avatar]),:onerror => "this.src='/data/no-image.jpg'", :class => "img-polaroid", :width => "215" %><br/>
		    	<%= f.file_field :avatar %>
		    </div>
	    </div>
	    <div class="control-group">
		    <div class="controls">
		    <button type="submit" class="btn">Save</button>
		    </div>
	    </div>
    <% end %>
    <script type="text/javascript">
    	$(document).ready(function() {
    		$(".alert").alert();
		});
    </script>

app/views/user/signup.html.erb
	<%= render :partial =>"home/breadcrum", :locals => { :current_page => @title} %>
	<h2>Register</h2>

	<%= signup_error %>

    <%= form_for @new_user, :url => signup_path, :html => { :class => "form-horizontal" } do |f| %>
	    <div  <%= status_input(:username) %> >
		    <label class="control-label" for="inputEmail">Email</label>
		    <div class="controls">
		    	<%= f.text_field :username,  :id => "inputEmail", :placeholder => "Email"  %>
		    </div>
	    </div>
	    <div <%= status_input(:password) %> >
		    <label class="control-label" for="inputPassword">Password</label>
		    <div class="controls">
		    	<%= f.text_field :password,  :id => "inputPassword", :placeholder => "Password", :type => "password"  %>
		    </div>
	    </div>
	    <div <%= status_input(:password_confirmation) %> >
		    <label class="control-label" for="inputPassword">Re-Password</label>
		    <div class="controls">
		    	<%= f.text_field :password_confirmation,  :id => "inputPassword", :placeholder => "Re-Password", :type => "password"  %>
		    </div>
	    </div>
	    <div class="control-group">
		    <div class="controls">
		    <button type="submit" class="btn">Register Now</button>
		    </div>
	    </div>
    <% end %>
    <script type="text/javascript">
    	$(document).ready(function() {
    		$(".alert").alert();
		});
    </script>