config/routes.rb
Blog::Application.routes.draw do
  get "ajax/edit_post"
  match "edit_post" => "ajax#edit_post", :as => "edit_post"

  get "post/new"
  match "new_post" => "post#new", :as => "new_post"

  get "post/detail"

  get "post/edit"

  get "post/delete"
  match "delete_post/:id" => "post#delete", :as => "delete_post"

  get "user/login"
  match "login" => "user#login", :as => "login"

  get "user/logout"
  match "logout" => "user#logout", :as => "logout"

  get "user/profile"
  match "profile" => "user#profile", :as => "profile"

  get "user/signup"
  match "signup" => "user#signup", :as => "signup"

  get "home/index"

  root :to => "home#index"

end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < ApplicationController
    before_filter :require_login
    def index
     @page  = "AdminManage"
     @user = User.all
    end
    
 private

  def require_login
    if session[:admin].nil?
      redirect_to root_path
    end
  end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@page  = "home"
  	@all_post = Post.all(:order => "created_at DESC")
  	@all_post.collect do |p| 
  		p.comment.collect do |c|
  			@user_by_comment = User.find(c.user_id)
  			c[:user] = @user_by_comment
  		end
  	end
  end
end

app/helpers/home_helper.rb
module HomeHelper
	def set_active(page, current)
		if page == current
			"class='active'"
		end
	end

	def set_sidebar
		if session[:login].nil?
			render "user/login"
		else
			render :partial => "user/info", :locals => {:avatar => @avatar}
		end
	end

	def set_header
		if session[:login].nil?
			html = '<ul class="nav">'
			html+= "<li  #{set_active('home',@page)} >"
			html+=	link_to "Home", root_path 
			html+=	"</li>"
			html+=	"<li #{set_active('signup',@page)} >"
			html+=	link_to "Sign Up", signup_path
			html+=	"</li>"
			html+=	"</ul>"
		else
			html = '<ul class="nav">'
			html+= "<li  #{set_active('home',@page)} >"
			html+=	link_to "Home", root_path 
			html+=	"</li>"
			html+=	"</ul>"
			html+=    '<div class="btn-group" style="float:right;">'
			html+=		link_to session[:login], profile_path , :class => "btn"
			html+=	   '<button class="btn dropdown-toggle" data-toggle="dropdown">'
			html+=	   '<span class="caret"></span>'
			html+=	   '</button>'
			html+=	   '<ul class="dropdown-menu">'
			html+=		"<li>"
			html+=		link_to "Edit Profile", profile_path
			html+=		"</li>"
			html+=		"<li>"
			html+=		link_to "Sign Out", logout_path
			html+=		"</li>"
			html+=	   '</ul>'
			html+=    '</div>'
		end
		raw html
	end

	def change_date (date)
		date.getlocal.strftime("%I:%M%p - %d/%m/%Y")
	end

	def show_date(created, updated, id)
		if created == updated
			html = "<small style='float:right;'><i id='date_#{id}'></i></small>"
			html += "<small style='float:right;'>Post At : #{change_date(created)}</small>"
		else
			html = "<small style='float:right;'><i id='date_#{id}'>&nbsp;&nbsp;&nbsp;(Edit At : #{change_date(updated)}) </i></small>"
		    html +="<small style='float:right;'>Post At : #{change_date(created)}</small>"
		end
		raw html
	end

	def this_owner? (username,id)
		if session[:login] == username
			image_edit = image_tag "/images/edit.png", :width => "20"
			image_delete = image_tag "/images/delete.png", :width => "20"
			html = '<div style="float:right;">'
			html+=	link_to image_edit, "javascript:;", :onclick => "show_edit_post(#{id})"
			html+= " "
    		html+=	link_to image_delete, delete_post_path(id), :onclick => "return confirm('Are you sure ?')"
    		html+=  '</div>'
		end
		raw html
	end
end

app/views/admin/home/index.html.erb
<% if !flash[:success].nil? %>
<div class='alert alert-success fade in'><%= flash[:success] %></div>
<% elsif !flash[:error].nil? %>
<div class='alert alert-error fade in'><%= flash[:success] %></div>
<% end  %>
<table class="table table-striped" >
    <tr >
      <th>Id</th>
      <th>User Name</th>
      <th>User Avatar</th>
      <th>User Type</th>
      <th colspan='3'>Action</th>
    </tr>

  <% @user.each do |user| %>
    <tr >
      <td><%= user.user_id %></td>
      <td><%= image_tag show_avatar(user[:avatar]),:onerror => "this.src='/data/no-image.jpg'", :class => "img-polaroid", :width => "80" %></td>
      <td><%= user.username %></td>
      <td><% if  user.user_type==1%>
                    Admin
              <%  else %>
                    User
              <% end %>
      </td>
      <td><%= link_to 'Edit', user_profile_path(user) %></td>
      <td><%= link_to 'Destroy', delete_user_path(user), :method => :delete, :onclick => 'return confirm("Are You sure?")' %></td>
    </tr>
  <% end %>
  </table>